import {test,expect} from '@playwright/test';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAgUlEQVR4nOXOMQEAIAzAsFIh3PiXgiGQsaNRkHX3eYRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMRJnMQ5HZj2AZlIApewdRpHAAAAAElFTkSuQmCC','base64');
test('local session, upload, extraction, search and deletion',async({page})=>{
 await page.goto('/');
 await page.getByLabel('Local session key').fill('browser-test-only');
 await page.getByRole('button',{name:'Open workspace'}).click();
 await expect(page.getByRole('heading',{name:'Your next clean slate.'})).toBeVisible();
 // Rights-free synthetic fixture generated by the test setup.
 await page.locator('input[type=file]').setInputFiles({name:'red-square.png',mimeType:'image/png',buffer:Buffer.from(process.env.TEST_PNG_BASE64||png.toString('base64'),'base64')});
 await expect(page.getByRole('dialog')).toBeVisible({timeout:15000});
 await page.getByRole('button',{name:'Create clean image'}).click();
 await expect(page.locator('.job-status strong')).toHaveText('succeeded',{timeout:15000});
 await page.getByRole('button',{name:'foreground',exact:true}).first().click();
 await expect(page.locator('.result-image')).toBeVisible();
 await page.screenshot({path:'test-results/workspace.png',fullPage:true});
 await page.getByRole('button',{name:'Accept',exact:true}).click();
 await page.getByRole('button',{name:'Close editor'}).click();
 await page.getByRole('textbox',{name:'Search images'}).fill('red square');
 await page.getByRole('button',{name:'Find images'}).click();
 await expect(page.locator('.notice')).toContainText('Searched',{timeout:15000});
 await page.locator('.card').first().click();
 page.on('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Delete image'}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect(page.locator('.card')).toHaveCount(0);
});
test('mobile session layout',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await expect(page.getByRole('heading',{name:/A little room/})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
});
test('interactive points, restoration and mask upload',async({page})=>{
 await page.goto('/');await page.getByLabel('Local session key').fill('browser-test-only');await page.getByRole('button',{name:'Open workspace'}).click();
 await page.locator('input[type=file]').setInputFiles({name:'selection.png',mimeType:'image/png',buffer:png});
 await expect(page.getByRole('dialog')).toBeVisible({timeout:15000});
 const canvas=page.locator('canvas');const bounds=await canvas.boundingBox();if(!bounds)throw Error('missing canvas');
 await canvas.click({position:{x:bounds.width*.5,y:bounds.height*.5}});
 await page.getByLabel('Gentle denoise').check();await page.getByLabel('Bounded tone adjustment').check();
 await page.getByLabel('Output size').selectOption('2');
 await page.getByRole('button',{name:'Create clean image'}).click();await expect(page.locator('.job-status strong')).toHaveText('succeeded',{timeout:15000});
 const firstJob=await page.locator('.job-status').getAttribute('data-job-id');
 await page.getByLabel('Erase painted area').check();await canvas.click({position:{x:bounds.width*.5,y:bounds.height*.5}});
 await page.getByRole('button',{name:'Create clean image'}).click();await expect(page.locator('.job-status')).not.toHaveAttribute('data-job-id',firstJob!);await expect(page.locator('.job-status strong')).toHaveText('succeeded',{timeout:15000});
 await page.getByRole('button',{name:'Close editor'}).click();
});
