import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,Search,ArrowUpRight,Plus,Minus,Square,Paintbrush,Download,Trash2,X,Check,RotateCcw,SlidersHorizontal,Image as ImageIcon,Activity,ShieldCheck} from 'lucide-react';
import './style.css';

type Asset={id:string;filename:string;state:string;width:number;height:number;expires:number;error?:string;role:string};
type Job={job_id:string;kind:string;status:string;stage:string;warnings:string[];error?:{detail:string};result?:{artifacts?:Record<string,string>;needs_review?:boolean;results?:{asset_id:string;score:number}[];indexed?:number;total?:number}};
type Point={x:number;y:number;label:0|1};
type Box={x_min:number;y_min:number;x_max:number;y_max:number};
let csrf='';
async function api(path:string,method='GET',body?:unknown){
 const r=await fetch(path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':csrf}:{}),...(path==='/v1/jobs'?{'Idempotency-Key':crypto.randomUUID()}:{})},body:body?JSON.stringify(body):undefined});
 const data=await r.json();if(!r.ok)throw Error(data.detail||data.title||'Request failed');return data;
}
async function waitAsset(id:string):Promise<Asset>{for(let i=0;i<1800;i++){const a=await api('/v1/assets/'+id);if(a.state==='ready')return a;if(a.state==='failed')throw Error(a.error);await new Promise(r=>setTimeout(r,1000));}throw Error('Validation timed out');}
async function uploadBlob(blob:Blob,filename:string,role='original',parent?:string){
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');
 const reservation=await api('/v1/uploads','POST',{filename,mime:blob.type,bytes:blob.size,sha256:hash,role,...(parent?{parent_asset_id:parent}:{})});
 const r=await fetch(reservation.upload_url,{method:'PUT',body:blob,headers:{'Content-Type':blob.type}});if(!r.ok)throw Error((await r.json()).detail);
 await api('/v1/uploads/'+reservation.asset_id+'/complete','POST');return waitAsset(reservation.asset_id);
}
function App(){
 const [authenticated,setAuthenticated]=useState(false),[secret,setSecret]=useState(''),[error,setError]=useState('');
 const [assets,setAssets]=useState<Asset[]>([]),[jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<Asset|null>(null);
 const [query,setQuery]=useState(''),[searchJob,setSearchJob]=useState<Job|null>(null),[searchIds,setSearchIds]=useState<string[]|null>(null);
 const [busy,setBusy]=useState(false),[caps,setCaps]=useState<any>(null),[showCaps,setShowCaps]=useState(false),[consent,setConsent]=useState(false);
 const [notice,setNotice]=useState(''),[mode,setMode]=useState('automatic'),[tool,setTool]=useState('positive');
 const [points,setPoints]=useState<Point[]>([]),[box,setBox]=useState<Box|null>(null),[denoise,setDenoise]=useState(false),[tone,setTone]=useState(false),[scale,setScale]=useState(1);
 const [fallback,setFallback]=useState(false),[inpaint,setInpaint]=useState(false),[memory,setMemory]=useState(false),[format,setFormat]=useState('png'),[background,setBackground]=useState('#ffffff');
 const [transparent,setTransparent]=useState(true),[preview,setPreview]=useState('original'),[brushSize,setBrushSize]=useState(24);
 const [hasMask,setHasMask]=useState(false),[zoom,setZoom]=useState(1),[feedbackRevision,setFeedbackRevision]=useState(0);
 const canvas=useRef<HTMLCanvasElement>(null),mask=useRef<HTMLCanvasElement|null>(null),image=useRef<HTMLImageElement|null>(null),drag=useRef<{x:number;y:number}|null>(null),file=useRef<HTMLInputElement>(null);
 async function refresh(){const [a,j]=await Promise.all([api('/v1/assets'),api('/v1/jobs')]);setAssets(a);setJobs(j);}
 useEffect(()=>{api('/v1/session').then(s=>{csrf=s.csrf;setConsent(s.consent);setAuthenticated(true)}).catch(()=>{});},[]);
 useEffect(()=>{if(!authenticated)return;refresh().catch(e=>setError(e.message));api('/v1/operations').then(setCaps).catch(e=>setError(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),2500);return()=>clearInterval(timer)},[authenticated]);
 useEffect(()=>{if(!searchJob)return;let closed=false;const timer=setInterval(async()=>{try{const j=await api('/v1/searches/'+searchJob.job_id);if(closed)return;if(j.status==='succeeded'){setSearchIds(j.result.results.map((r:any)=>r.asset_id));setNotice(`Searched ${j.result.indexed} of ${j.result.total} images`);setSearchJob(null);}else if(j.status==='failed'){setError(j.error.detail);setSearchJob(null)}}catch(e){setError(String(e));setSearchJob(null)}},1000);return()=>{closed=true;clearInterval(timer)}},[searchJob]);
 const [selectedJobs,setSelectedJobs]=useState<Job[]>([]);
 useEffect(()=>{if(!selected)return;api('/v1/jobs?asset_id='+selected.id).then(setSelectedJobs).catch(()=>{});},[selected,jobs]);
 const latest=selectedJobs.find(j=>j.kind==='image');
 useEffect(()=>{if(!latest)return;api(`/v1/jobs/${latest.job_id}/feedback`).then(f=>setFeedbackRevision(f.revision)).catch(()=>{});},[latest?.job_id]);
 useEffect(()=>{if(!latest||['succeeded','failed','canceled'].includes(latest.status))return;const stream=new EventSource(`/v1/jobs/${latest.job_id}/events`);stream.onmessage=()=>refresh().catch(()=>{});stream.onerror=()=>stream.close();return()=>stream.close()},[latest?.job_id]);
 function reset(a:Asset){setSelected(a);setPoints([]);setBox(null);setHasMask(false);setPreview('original');setMode('automatic');setInpaint(false);setZoom(1);setFeedbackRevision(0);mask.current=null;}
 useEffect(()=>{if(!selected)return;const im=new window.Image();im.onload=()=>{image.current=im;if(!mask.current){mask.current=document.createElement('canvas');mask.current.width=selected.width;mask.current.height=selected.height;}draw();};im.src='/v1/assets/'+selected.id+'/content';},[selected]);
 function draw(){const c=canvas.current,im=image.current;if(!c||!im||!selected)return;c.width=selected.width;c.height=selected.height;const ctx=c.getContext('2d')!;ctx.drawImage(im,0,0,c.width,c.height);if(mask.current){ctx.save();ctx.globalAlpha=.45;ctx.drawImage(mask.current,0,0);ctx.restore();}const radius=Math.max(5,c.width/110);for(const p of points){ctx.beginPath();ctx.arc(p.x*(c.width-1),p.y*(c.height-1),radius,0,Math.PI*2);ctx.fillStyle=p.label?'#b8ec83':'#ef886f';ctx.fill();ctx.strokeStyle='#143428';ctx.lineWidth=radius/3;ctx.stroke();}if(box){ctx.strokeStyle='#b8ec83';ctx.lineWidth=radius/2;ctx.strokeRect(box.x_min*(c.width-1),box.y_min*(c.height-1),(box.x_max-box.x_min)*(c.width-1),(box.y_max-box.y_min)*(c.height-1));}}
 useEffect(draw,[points,box,selected,preview,hasMask,zoom]);
 function position(e:React.PointerEvent){const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
 function paint(p:{x:number;y:number}){if(!mask.current)return;const ctx=mask.current.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(p.x*(mask.current.width-1),p.y*(mask.current.height-1),brushSize/2,0,Math.PI*2);ctx.fill();setHasMask(true);draw();}
 function pointerDown(e:React.PointerEvent<HTMLCanvasElement>){if(preview!=='original')return;e.currentTarget.setPointerCapture(e.pointerId);const p=position(e);drag.current=p;if(tool==='positive'||tool==='negative'){if(points.length>=32){setError('Maximum 32 points');return}setPoints([...points,{...p,label:tool==='positive'?1:0}]);setMode('interactive');}else if(tool==='brush'){paint(p)}}
 function pointerMove(e:React.PointerEvent<HTMLCanvasElement>){if(!drag.current)return;const p=position(e);if(tool==='brush')paint(p);if(tool==='box'){setBox({x_min:Math.min(p.x,drag.current.x),y_min:Math.min(p.y,drag.current.y),x_max:Math.max(p.x,drag.current.x),y_max:Math.max(p.y,drag.current.y)});setMode('interactive')}}
 async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function upload(files:FileList|null){if(!files)return;await act(async()=>{for(const f of Array.from(files)){setNotice('Validating '+f.name);const a=await uploadBlob(f,f.name);await api('/v1/assets/'+a.id+'/index','POST');reset(a);}await refresh();setNotice('Upload complete. Choose an operation to begin.');})}
 async function process(){if(!selected)return;await act(async()=>{let maskId:string|undefined;if(hasMask&&mask.current){const black=document.createElement('canvas');black.width=mask.current.width;black.height=mask.current.height;const ctx=black.getContext('2d')!;ctx.fillStyle='black';ctx.fillRect(0,0,black.width,black.height);ctx.drawImage(mask.current,0,0);const blob=await new Promise<Blob>(resolve=>black.toBlob(b=>resolve(b!),'image/png'));maskId=(await uploadBlob(blob,'mask.png',inpaint?'erase_mask':'refinement_mask',selected.id)).id;}
 const request={input_asset_id:selected.id,segmentation:{mode,allow_lightweight_fallback:fallback,...(mode==='interactive'?{points,box,...(!inpaint&&maskId?{refinement_mask_asset_id:maskId}:{})}:{})},restoration:{denoise:denoise?'classical':'off',deblur:'off',tone:tone?'classical':'off',strength:.2},upscale:{scale,method:'lanczos'},output:{format,background:format==='png'&&transparent?'transparent':background},memory:{allow_indexing:memory},...(inpaint?{inpaint:{erase_mask_asset_id:maskId,method:'classical',feather_px:2}}:{})};
 if(inpaint&&!maskId)throw Error('Paint the area to erase first');await api('/v1/jobs','POST',request);setNotice('Job queued. You can continue browsing.');await refresh();})}
 async function download(id:string){await act(async()=>{const r=await api('/v1/assets/'+id+'/download','POST');const a=document.createElement('a');a.href=r.url;a.click();})}
 const shown=searchIds?searchIds.map(id=>assets.find(a=>a.id===id)).filter(Boolean) as Asset[]:assets;
 if(!authenticated)return <main className="login"><div className="brand"><span className="brand-mark">s.</span>stillroom</div><p className="eyebrow">YOUR LOCAL IMAGE WORKSPACE</p><h1>A little room<br/>for a cleaner image.</h1><p>Private processing. Original files preserved.<br/>Start a session using the key shown by the local launcher.</p><form onSubmit={e=>{e.preventDefault();act(async()=>{const s=await api('/v1/session/bootstrap','POST',{secret});csrf=s.csrf;setAuthenticated(true);setSecret('')})}}><label htmlFor="secret">Local session key</label><input id="secret" type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="off" required/><button disabled={busy}>Open workspace <ArrowUpRight size={16}/></button></form>{error&&<p role="alert" className="error">{error}</p>}<small>Run <code>image-cleaning session-key</code> in your terminal.</small></main>;
 return <><header><a className="brand" href="/"><span className="brand-mark">s.</span>stillroom</a><nav><span className="local-dot"/> LOCAL WORKSPACE <button className="quiet" onClick={()=>setShowCaps(!showCaps)}><Activity size={16}/> System</button></nav></header>
 <main><section className="intro"><div><p className="eyebrow">LESS BACKGROUND. MORE POSSIBILITY.</p><h1>Make space for<br/><em>the subject.</em></h1></div><p className="intro-copy">Extract, refine, and rediscover your images.<br/>Everything stays right here, on your Mac.</p></section>
 {error&&<div className="error banner" role="alert">{error}<button className="quiet" onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {notice&&<div className="notice" role="status">{notice}</div>}
 {showCaps&&<section className="system"><h2>Local capabilities</h2><div className="models">{caps&&Object.entries(caps.models).map(([name,m]:[string,any])=><div key={name}><strong>{name}</strong><span>{m.available?'Provisioned':'Setup required'}</span><small>{m.reason||`Qualified devices: ${m.qualified_devices.join(', ')||'awaiting benchmark'}`}</small></div>)}</div><p>One model at a time · 12 MP input · 16 MP output · 30-day retention</p><label><input type="checkbox" checked={consent} onChange={e=>{const enabled=e.target.checked;act(async()=>{await api('/v1/consent','PUT',{enabled});setConsent(enabled)})}}/> Allow accepted results to become private workflow examples</label><p className="hint">Each job also needs your permission. Revoking consent immediately excludes previous examples.</p></section>}
 <section className="workspace"><aside className="upload-panel"><p className="eyebrow">01 / BRING IT IN</p><h2>Your next clean slate.</h2><button className="dropzone" disabled={busy} onClick={()=>file.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files)}}><Upload size={30} strokeWidth={1.2}/><strong>{busy?'Working…':'Drop an image here'}</strong><span>or choose a file</span><small>PNG, JPEG, WebP · up to 25 MiB</small></button><input hidden ref={file} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>upload(e.target.files)}/><p className="hint"><ShieldCheck size={15}/> Originals stay untouched. Processing and search run locally.</p><div className="queue"><h3>Activity</h3>{jobs.filter(j=>!['succeeded','canceled'].includes(j.status)).slice(0,5).map(j=><div key={j.job_id}><span>{j.kind} · {j.stage}</span><small>{j.error?.detail||j.status}</small>{j.status==='failed'?<button className="quiet" onClick={()=>act(()=>api(`/v1/jobs/${j.job_id}/retry`,'POST'))}>Retry</button>:<button className="quiet" onClick={()=>act(()=>api(`/v1/jobs/${j.job_id}/cancel`,'POST'))}>Cancel</button>}</div>)}</div></aside>
 <section className="library"><div className="section-head"><div><p className="eyebrow">02 / YOUR COLLECTION</p><h2>Ready for a second look.</h2></div><span className="count">{assets.length} images</span></div><form className="search" onSubmit={e=>{e.preventDefault();act(async()=>setSearchJob(await api('/v1/searches','POST',{query,limit:24})))}}><Search size={20}/><input aria-label="Search images" placeholder="Try ‘a red leather bag’" value={query} onChange={e=>setQuery(e.target.value)}/>{searchIds&&<button type="button" className="quiet" onClick={()=>{setSearchIds(null);setQuery('')}}>Clear</button>}<button disabled={busy||!!searchJob||!query.trim()}>{searchJob?'Searching…':'Find images'} <ArrowUpRight size={15}/></button></form>
 <div className="library-toolbar"><span>{searchIds?'SEARCH RESULTS':'ALL IMAGES'}</span><span>Originals & reusable assets</span></div><div className="grid">{shown.map(a=><button className="card" key={a.id} onClick={()=>reset(a)} disabled={a.state!=='ready'}><div className="picture checker">{a.state==='ready'?<img src={'/v1/assets/'+a.id+'/content'} alt={a.filename}/>:<ImageIcon/>}</div><div className="card-meta"><strong>{a.filename}</strong><small>{a.width?`${a.width} × ${a.height}`:a.state}<ArrowUpRight size={14}/></small></div></button>)}{!shown.length&&<div className="empty"><ImageIcon size={34} strokeWidth={1}/><h3>{searchIds?'No matches yet.':'A fresh start.'}</h3><p>{searchIds?'Try another description or index your images.':'Add your first image to begin.'}</p></div>}</div></section></section>
 </main><footer><span>STILLROOM / LOCAL IMAGE CLEANING</span><span>A quieter way to work with images.</span></footer>
 {selected&&<div className="overlay"><section className="editor" role="dialog" aria-modal="true" aria-labelledby="editor-title"><div className="editor-head"><div><p className="eyebrow">IMAGE WORKSPACE</p><h2 id="editor-title">{selected.filename}</h2></div><button className="quiet" aria-label="Close editor" onClick={()=>setSelected(null)}><X/></button></div>{error&&<p className="error" role="alert">{error}</p>}<div className="editor-layout"><div><div className="canvas-scroll checker"><div style={{width:`${zoom*100}%`}}>{preview==='original'?<canvas ref={canvas} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}/>:<img className="result-image" src={'/v1/assets/'+latest?.result?.artifacts?.[preview]+'/content?representation=original'} alt={preview}/>}</div></div><div className="tools">{[['positive',Plus,'Keep point'],['negative',Minus,'Exclude point'],['box',Square,'Box'],['brush',Paintbrush,inpaint?'Erase brush':'Keep brush']].map(([key,Icon,label]:any)=><button key={key} className={tool===key?'active':'quiet'} onClick={()=>{setTool(key);setPreview('original');if(key==='brush'&&!inpaint)setMode('interactive')}}><Icon size={16}/>{label}</button>)}<button className="quiet" onClick={()=>{setPoints([]);setBox(null);mask.current?.getContext('2d')?.clearRect(0,0,selected.width,selected.height);setHasMask(false);draw()}}><RotateCcw size={15}/>Reset</button></div><label className="range">Zoom<input type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label>{tool==='brush'&&<label className="range">Brush pixels<input type="range" min="2" max="150" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/></label>}
 <div className="tabs"><button className={preview==='original'?'active':'quiet'} onClick={()=>setPreview('original')}>Original</button>{latest?.result?.artifacts&&['foreground','conservative','preview'].map(role=><button key={role} className={preview===role?'active':'quiet'} onClick={()=>setPreview(role)}>{role}</button>)}</div><small className="hint">Points and masks refer to the oriented original. Scroll the canvas when zoomed.</small></div>
 <aside className="controls"><h3><SlidersHorizontal size={17}/> Process image</h3><label>Selection<select aria-label="Selection mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="automatic">Automatic foreground</option><option value="interactive">Interactive selection</option><option value="none">Keep full image</option></select></label>{mode==='automatic'&&<label><input type="checkbox" checked={fallback} onChange={e=>setFallback(e.target.checked)}/> Allow lightweight fallback if needed</label>}<fieldset><legend>Optional restoration</legend><label><input type="checkbox" checked={denoise} onChange={e=>setDenoise(e.target.checked)}/> Gentle denoise</label><label><input type="checkbox" checked={tone} onChange={e=>setTone(e.target.checked)}/> Bounded tone adjustment</label><label><input type="checkbox" checked={inpaint} onChange={e=>{setInpaint(e.target.checked);mask.current?.getContext('2d')?.clearRect(0,0,selected.width,selected.height);setHasMask(false);setTool('brush');draw()}}/> Erase painted area</label></fieldset><label>Size<select aria-label="Output size" value={scale} onChange={e=>setScale(+e.target.value)}><option value="1">Original size</option><option value="2">2× Lanczos</option></select></label><label>Export<select aria-label="Export format" value={format} onChange={e=>setFormat(e.target.value)}><option value="png">PNG</option><option value="jpeg">JPEG</option></select></label>{format==='png'&&<label><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/> Transparent background</label>}{(format==='jpeg'||!transparent)&&<label>Background<input type="color" value={background} onChange={e=>setBackground(e.target.value)}/></label>}<label><input type="checkbox" checked={memory} disabled={!consent} onChange={e=>setMemory(e.target.checked)}/> Use if I accept this result</label><button className="primary" disabled={busy} onClick={process}>Create clean image <ArrowUpRight size={16}/></button>
 {latest&&<div className="job-status" data-job-id={latest.job_id}><strong>{latest.status.replaceAll('_',' ')}</strong><span>{latest.error?.detail||latest.stage}</span>{latest.warnings.map(w=><small key={w}>{w.replaceAll('_',' ')}</small>)}</div>}
 {latest?.result?.artifacts&&<><h3>Downloads</h3><div className="downloads">{Object.entries(latest.result.artifacts).map(([role,id])=><button className="quiet" key={role} onClick={()=>download(id)}><Download size={14}/>{role.replaceAll('_',' ')}</button>)}</div><div className="feedback"><button onClick={()=>act(async()=>{await api(`/v1/jobs/${latest.job_id}/feedback`,'POST',{accepted:true,revision:feedbackRevision+1,reason:''});setFeedbackRevision(feedbackRevision+1);setNotice('Feedback saved')})}><Check size={14}/>Accept</button><button className="quiet" onClick={()=>act(async()=>{await api(`/v1/jobs/${latest.job_id}/feedback`,'POST',{accepted:false,revision:feedbackRevision+1,reason:''});setFeedbackRevision(feedbackRevision+1)})}>Reject</button><button className="quiet" onClick={()=>act(async()=>{const p=await api(`/v1/jobs/${latest.job_id}/plan`);setNotice(`Recipe: ${p.workflow}. ${p.reason}`)})}>Recipe</button></div></>}
 <p className="hint">Expires {new Date(selected.expires*1000).toLocaleDateString()}</p><button className="quiet" onClick={()=>act(()=>api('/v1/assets/'+selected.id+'/index','POST'))}>Update search index</button><button className="quiet" onClick={()=>download(selected.id)}><Download size={14}/> Original</button><button className="danger quiet" onClick={()=>{if(confirm('Delete this original and all derived assets?'))act(async()=>{await api('/v1/assets/'+selected.id,'DELETE');setSelected(null);await refresh()})}}><Trash2 size={14}/>Delete image</button></aside></div></section></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
